import { Element } from "@/types";
import { atom } from "jotai";
import { nanoid } from "nanoid";

const ids = [
    nanoid(),
    nanoid(),
    nanoid(),
    nanoid(),
    nanoid(),
    nanoid(),
    nanoid(),
    nanoid(),
    nanoid(),
    nanoid(),
    nanoid(),
    nanoid(),
    nanoid(),
];

export const elementsAtom = atom<{ [key: Element["uid"]]: Element }>({
    [ids[0]]: {
        uid: ids[0],
        x: 0,
        y: 0,
        width: 64,
        height: 64,
        type: "and_gate",
        zIndex: 0,
        nonce: 0,
    },
    [ids[1]]: {
        uid: ids[1],
        x: 64,
        y: 64,
        width: 64,
        height: 64,
        type: "or_gate",
        zIndex: 0,
        nonce: 10,
    },
    [ids[2]]: {
        uid: ids[2],
        x: 128,
        y: 128,
        width: 64,
        height: 64,
        type: "not_gate",
        zIndex: 0,
        nonce: 20,
    },
    [ids[3]]: {
        uid: ids[3],
        x: 64,
        y: 0,
        width: 64,
        height: 64,
        type: "nand_gate",
        zIndex: 0,
        nonce: 23,
    },
    [ids[4]]: {
        uid: ids[4],
        x: 0,
        y: 64,
        width: 64,
        height: 64,
        type: "nor_gate",
        zIndex: 0,
        nonce: 23,
    },
    [ids[5]]: {
        uid: ids[5],
        x: 0,
        y: 128,
        width: 64,
        height: 64,
        type: "buffer",
        zIndex: 0,
        nonce: 23,
    },
    [ids[6]]: {
        uid: ids[6],
        x: 128,
        y: 64,
        width: 64,
        height: 64,
        type: "xor_gate",
        zIndex: 0,
        nonce: 23,
    },
    [ids[7]]: {
        uid: ids[7],
        x: 128,
        y: 0,
        width: 64,
        height: 64,
        type: "xnor_gate",
        zIndex: 0,
        nonce: 23,
    },
    [ids[8]]: {
        uid: ids[8],
        x: 0,
        y: 192,
        width: 64,
        height: 64,
        type: "mux",
        zIndex: 0,
        nonce: 23,
    },
    [ids[9]]: {
        uid: ids[9],
        x: 64,
        y: 192,
        width: 64,
        height: 64,
        type: "dmux",
        zIndex: 0,
        nonce: 23,
    },
    [ids[10]]: {
        uid: ids[10],
        x: 128,
        y: 192,
        width: 64,
        height: 64,
        type: "decoder",
        zIndex: 0,
        nonce: 23,
    },
    [ids[11]]: {
        uid: ids[11],
        x: 192,
        y: 256,
        width: 64,
        height: 64,
        type: "DQ_flip_flop",
        zIndex: 0,
        nonce: 23,
    },
});
